# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pull request linter action
      # You may pin to the exact commit or the version.
      # uses: JulienKode/pull-request-name-linter-action@2d32d4e7eb34ae4ff9c3c3ba0f5eaadb27bb0f2d
      uses: JulienKode/pull-request-name-linter-action@v0.2.0
      with:
        # The path for the commitlint configurations
        configuration-path: ./commitlint.prod.config.js
    #- name: npm install, validate
     # run: |
    #    npm ci
     #   echo {{github.context.payload?.pull_request}}

